const { test, expect }  = require('@playwright/test')

test('Playwright smart locators', async ({page})=>{
    await page.goto("https://rahulshettyacademy.com/angularpractice/")
    await page.getByLabel("Password").fill("vig@yopmail.com")
    await page.getByLabel("Check me out if you Love IceCreams!").check()
    await page.getByLabel("Employed").check()
    await page.getByLabel("Gender").selectOption("Female")
    await page.getByPlaceholder("Password").fill("abcd1234")
    await page.getByRole("button",{name:"submit"}).click()
    const msg = await page.getByText(" The Form has been submitted successfully!.")
    await expect(msg).toBeTruthy()
    await page.getByRole("link",{name:"Shop"}).click()
    await page.locator("app-card").filter({ hasText :"Nokia Edge"}).getByRole("button").click()
})